/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HipaaComplianceRouteImport } from './routes/hipaa-compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesPriorAuthorizationsRouteImport } from './routes/services.prior-authorizations'
import { Route as ServicesPracticeOperationsRouteImport } from './routes/services.practice-operations'
import { Route as ServicesPaymentPostingRouteImport } from './routes/services.payment-posting'
import { Route as ServicesInsuranceVerificationRouteImport } from './routes/services.insurance-verification'
import { Route as ServicesClaimSubmissionRouteImport } from './routes/services.claim-submission'
import { Route as ServicesAnalyticsReportingRouteImport } from './routes/services.analytics-reporting'
import { Route as ServicesAccountsReceivableRouteImport } from './routes/services.accounts-receivable'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaComplianceRoute = HipaaComplianceRouteImport.update({
  id: '/hipaa-compliance',
  path: '/hipaa-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPriorAuthorizationsRoute =
  ServicesPriorAuthorizationsRouteImport.update({
    id: '/prior-authorizations',
    path: '/prior-authorizations',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPracticeOperationsRoute =
  ServicesPracticeOperationsRouteImport.update({
    id: '/practice-operations',
    path: '/practice-operations',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPaymentPostingRoute = ServicesPaymentPostingRouteImport.update({
  id: '/payment-posting',
  path: '/payment-posting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesInsuranceVerificationRoute =
  ServicesInsuranceVerificationRouteImport.update({
    id: '/insurance-verification',
    path: '/insurance-verification',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesClaimSubmissionRoute = ServicesClaimSubmissionRouteImport.update({
  id: '/claim-submission',
  path: '/claim-submission',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAnalyticsReportingRoute =
  ServicesAnalyticsReportingRouteImport.update({
    id: '/analytics-reporting',
    path: '/analytics-reporting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAccountsReceivableRoute =
  ServicesAccountsReceivableRouteImport.update({
    id: '/accounts-receivable',
    path: '/accounts-receivable',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/analytics-reporting': typeof ServicesAnalyticsReportingRoute
  '/services/claim-submission': typeof ServicesClaimSubmissionRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
  '/services/payment-posting': typeof ServicesPaymentPostingRoute
  '/services/practice-operations': typeof ServicesPracticeOperationsRoute
  '/services/prior-authorizations': typeof ServicesPriorAuthorizationsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/analytics-reporting': typeof ServicesAnalyticsReportingRoute
  '/services/claim-submission': typeof ServicesClaimSubmissionRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
  '/services/payment-posting': typeof ServicesPaymentPostingRoute
  '/services/practice-operations': typeof ServicesPracticeOperationsRoute
  '/services/prior-authorizations': typeof ServicesPriorAuthorizationsRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/analytics-reporting': typeof ServicesAnalyticsReportingRoute
  '/services/claim-submission': typeof ServicesClaimSubmissionRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
  '/services/payment-posting': typeof ServicesPaymentPostingRoute
  '/services/practice-operations': typeof ServicesPracticeOperationsRoute
  '/services/prior-authorizations': typeof ServicesPriorAuthorizationsRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/analytics-reporting'
    | '/services/claim-submission'
    | '/services/insurance-verification'
    | '/services/payment-posting'
    | '/services/practice-operations'
    | '/services/prior-authorizations'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/analytics-reporting'
    | '/services/claim-submission'
    | '/services/insurance-verification'
    | '/services/payment-posting'
    | '/services/practice-operations'
    | '/services/prior-authorizations'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/analytics-reporting'
    | '/services/claim-submission'
    | '/services/insurance-verification'
    | '/services/payment-posting'
    | '/services/practice-operations'
    | '/services/prior-authorizations'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HipaaComplianceRoute: typeof HipaaComplianceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa-compliance': {
      id: '/hipaa-compliance'
      path: '/hipaa-compliance'
      fullPath: '/hipaa-compliance'
      preLoaderRoute: typeof HipaaComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/prior-authorizations': {
      id: '/services/prior-authorizations'
      path: '/prior-authorizations'
      fullPath: '/services/prior-authorizations'
      preLoaderRoute: typeof ServicesPriorAuthorizationsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/practice-operations': {
      id: '/services/practice-operations'
      path: '/practice-operations'
      fullPath: '/services/practice-operations'
      preLoaderRoute: typeof ServicesPracticeOperationsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/payment-posting': {
      id: '/services/payment-posting'
      path: '/payment-posting'
      fullPath: '/services/payment-posting'
      preLoaderRoute: typeof ServicesPaymentPostingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/insurance-verification': {
      id: '/services/insurance-verification'
      path: '/insurance-verification'
      fullPath: '/services/insurance-verification'
      preLoaderRoute: typeof ServicesInsuranceVerificationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/claim-submission': {
      id: '/services/claim-submission'
      path: '/claim-submission'
      fullPath: '/services/claim-submission'
      preLoaderRoute: typeof ServicesClaimSubmissionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/analytics-reporting': {
      id: '/services/analytics-reporting'
      path: '/analytics-reporting'
      fullPath: '/services/analytics-reporting'
      preLoaderRoute: typeof ServicesAnalyticsReportingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/accounts-receivable': {
      id: '/services/accounts-receivable'
      path: '/accounts-receivable'
      fullPath: '/services/accounts-receivable'
      preLoaderRoute: typeof ServicesAccountsReceivableRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAccountsReceivableRoute: typeof ServicesAccountsReceivableRoute
  ServicesAnalyticsReportingRoute: typeof ServicesAnalyticsReportingRoute
  ServicesClaimSubmissionRoute: typeof ServicesClaimSubmissionRoute
  ServicesInsuranceVerificationRoute: typeof ServicesInsuranceVerificationRoute
  ServicesPaymentPostingRoute: typeof ServicesPaymentPostingRoute
  ServicesPracticeOperationsRoute: typeof ServicesPracticeOperationsRoute
  ServicesPriorAuthorizationsRoute: typeof ServicesPriorAuthorizationsRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAccountsReceivableRoute: ServicesAccountsReceivableRoute,
  ServicesAnalyticsReportingRoute: ServicesAnalyticsReportingRoute,
  ServicesClaimSubmissionRoute: ServicesClaimSubmissionRoute,
  ServicesInsuranceVerificationRoute: ServicesInsuranceVerificationRoute,
  ServicesPaymentPostingRoute: ServicesPaymentPostingRoute,
  ServicesPracticeOperationsRoute: ServicesPracticeOperationsRoute,
  ServicesPriorAuthorizationsRoute: ServicesPriorAuthorizationsRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HipaaComplianceRoute: HipaaComplianceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
