/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HipaaComplianceRouteImport } from './routes/hipaa-compliance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesInsuranceVerificationRouteImport } from './routes/services.insurance-verification'
import { Route as ServicesDentalBillingRouteImport } from './routes/services.dental-billing'
import { Route as ServicesCredentialingRouteImport } from './routes/services.credentialing'
import { Route as ServicesAccountsReceivableRouteImport } from './routes/services.accounts-receivable'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HipaaComplianceRoute = HipaaComplianceRouteImport.update({
  id: '/hipaa-compliance',
  path: '/hipaa-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInsuranceVerificationRoute =
  ServicesInsuranceVerificationRouteImport.update({
    id: '/insurance-verification',
    path: '/insurance-verification',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDentalBillingRoute = ServicesDentalBillingRouteImport.update({
  id: '/dental-billing',
  path: '/dental-billing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCredentialingRoute = ServicesCredentialingRouteImport.update({
  id: '/credentialing',
  path: '/credentialing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAccountsReceivableRoute =
  ServicesAccountsReceivableRouteImport.update({
    id: '/accounts-receivable',
    path: '/accounts-receivable',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/credentialing': typeof ServicesCredentialingRoute
  '/services/dental-billing': typeof ServicesDentalBillingRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/credentialing': typeof ServicesCredentialingRoute
  '/services/dental-billing': typeof ServicesDentalBillingRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/hipaa-compliance': typeof HipaaComplianceRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/accounts-receivable': typeof ServicesAccountsReceivableRoute
  '/services/credentialing': typeof ServicesCredentialingRoute
  '/services/dental-billing': typeof ServicesDentalBillingRoute
  '/services/insurance-verification': typeof ServicesInsuranceVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/credentialing'
    | '/services/dental-billing'
    | '/services/insurance-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/credentialing'
    | '/services/dental-billing'
    | '/services/insurance-verification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/hipaa-compliance'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/services/accounts-receivable'
    | '/services/credentialing'
    | '/services/dental-billing'
    | '/services/insurance-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  HipaaComplianceRoute: typeof HipaaComplianceRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipaa-compliance': {
      id: '/hipaa-compliance'
      path: '/hipaa-compliance'
      fullPath: '/hipaa-compliance'
      preLoaderRoute: typeof HipaaComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/insurance-verification': {
      id: '/services/insurance-verification'
      path: '/insurance-verification'
      fullPath: '/services/insurance-verification'
      preLoaderRoute: typeof ServicesInsuranceVerificationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dental-billing': {
      id: '/services/dental-billing'
      path: '/dental-billing'
      fullPath: '/services/dental-billing'
      preLoaderRoute: typeof ServicesDentalBillingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/credentialing': {
      id: '/services/credentialing'
      path: '/credentialing'
      fullPath: '/services/credentialing'
      preLoaderRoute: typeof ServicesCredentialingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/accounts-receivable': {
      id: '/services/accounts-receivable'
      path: '/accounts-receivable'
      fullPath: '/services/accounts-receivable'
      preLoaderRoute: typeof ServicesAccountsReceivableRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesAccountsReceivableRoute: typeof ServicesAccountsReceivableRoute
  ServicesCredentialingRoute: typeof ServicesCredentialingRoute
  ServicesDentalBillingRoute: typeof ServicesDentalBillingRoute
  ServicesInsuranceVerificationRoute: typeof ServicesInsuranceVerificationRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAccountsReceivableRoute: ServicesAccountsReceivableRoute,
  ServicesCredentialingRoute: ServicesCredentialingRoute,
  ServicesDentalBillingRoute: ServicesDentalBillingRoute,
  ServicesInsuranceVerificationRoute: ServicesInsuranceVerificationRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  HipaaComplianceRoute: HipaaComplianceRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
